services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    stdin_open: true
    tty: true
  dicend:
    build: ./dicend/dice-server
    ports:
      - "5000:5000"
    volumes:
      - ./dicend/dice-server:/app
    tty: true
