services:
  backend:
    container_name: diceogen-backend
    build: ./backend
    ports:
      - "8000:3000"
    volumes:
      - ./backend:/app
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - diceogen-network

  frontend:
    container_name: diceogen-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    stdin_open: true
    tty: true
    networks:
      - diceogen-network
  
  db:
    container_name: diceogen-db
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/schema.sql:/database/schema.sql
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - diceogen-network

  dicend:
    container_name: diceogen-dicend
    build: ./dicend/dice-server
    ports:
      - "5000:5000"
    volumes:
      - ./dicend/dice-server:/app
    tty: true

  proxy:
    container_name: diceogen-proxy
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - diceogen-network

volumes:
  db-store:

networks:
  diceogen-network:
