services:
  backend:
    build: ./backend
    ports:
      - "8000:3000"
    volumes:
      - ./backend:/app
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - NITRO_PORT=8000
